{% set name = "fifipy" %}
#{% set version = "0.4" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_tag: master
  git_url: https://github.com/darioflute/fifipy.git

build:
  
requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - matplotlib >=3.7
    - numpy >=1.23
    - scipy >=1.10
    - astropy >=5.1
    - pyqt >=5.15
        
test:
  imports:
    - fifipy
  commands:
    - cubik

about:
  home: https://github.com/darioflute/fifipy
  license: GPL3
  license_file: LICENSE
  description: 'Library for reduction of non-standard FIFI-LS data and visualization of cubes.'
