{% set name = "fifipy" %}
{% set version = "0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_tag: master
  git_url: https://github.com/darioflute/fifipy.git

build:
  
requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - matplotlib >=3.0.2
    - numpy >=1.11
    - scipy
    - astropy >=3.0
    - pyqt
        
test:
  imports:
    - fifipy
  commands:
    - cubik

about:
  home: https://github.com/darioflute/fifipy
  license: GPL3
  license_file: LICENSE
  description: 'Library for reduction of non-standard FIFI-LS data.'
